### ISSUE TITLE
[BUG]: crashes on world gen

### ISSUE THREAD

**Issue by rrnk235** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#48] opened 2023-03-25 23:12 UTC
### Description of the bug/crash

crashes when i try to generate a world idk which file to send so ima send both 

### Steps To Reproduce

tried to generate a normal world with large glacier frozen core geodes metal rich and geoactive it is the only mod i had instlled on my last attempt 

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070406/Player.log)
[Player-prev.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070408/Player-prev.log)

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:11
That log seems to point at a base game method breaking after a successful generation (for some reason).
Does the crash still occur after doing a file ntegrity check?
(rightclick in steam; "Properties", "Local Files", "Verify integrity of game files"

**Comment by rrnk235** [comment] 2023-03-26 00:13
yes 
i have done that it doesnt say any files failed to validate

**Comment by rrnk235** [comment] 2023-03-26 00:13
i will try once more just to see maybe it missed somthing

**Comment by rrnk235** [comment] 2023-03-26 00:14
yea allfiles validated

**Comment by rrnk235** [comment] 2023-03-26 00:17
i will try un modded just to see if something happens

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:18
try generating a normal cluster, with all the other mods active there might be other mods breaking something

**Comment by rrnk235** [comment] 2023-03-26 00:20
yea disabling the mod  it works fine in vanilla and modded other mods seem to work just fine

**Comment by rrnk235** [comment] 2023-03-26 00:25
i really appreciate you taking time outof youre day for this btw if i had some extra money deff would donate i will remember this lol

**Comment by rrnk235** [comment] 2023-03-26 00:32
with the mod by itself without touching anything and just hitting start its still crashes at space adventure awaits every time it doesnt seem like idividual setting affects it i may be wrong im not a mod author nor do i know code just trying to help narrow things down

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:35
Thats the weird part, it doesnt fail at the world gen, it fails after that is done, for some reason a part of the game scene fails to exist

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:36
could you provide me with a log that has only the CGM  mod active?

**Comment by rrnk235** [comment] 2023-03-26 00:36
yes just reinstalled itby itself ill send it shortly

**Comment by rrnk235** [comment] 2023-03-26 00:37
ummm so

**Comment by rrnk235** [comment] 2023-03-26 00:38
after reinstalling it worked

**Comment by rrnk235** [comment] 2023-03-26 00:38
maybe i had a corrupted install? idk

**Comment by rrnk235** [comment] 2023-03-26 00:39
let me full test ut b4 i count my ducks lol

**Comment by rrnk235** [comment] 2023-03-26 00:39
ohh new prob now the cog isnt showing up

**Comment by rrnk235** [comment] 2023-03-26 00:40
ok disregard what i said im an idiot that was a diff mod XD

**Comment by rrnk235** [comment] 2023-03-26 00:42
yes still crashed heres the log
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070494/Player.log)

**Comment by rrnk235** [comment] 2023-03-26 00:42
that should be it i hope

**Comment by rrnk235** [comment] 2023-03-26 00:43
it still looks like the other mods are in there do i need to insub from them to remove them or?

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:44
no, just uncheck them in the mod list

**Comment by rrnk235** [comment] 2023-03-26 00:45
i did

**Comment by rrnk235** [comment] 2023-03-26 00:46
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070497/Player.log)

**Comment by rrnk235** [comment] 2023-03-26 00:47
ok that should be the most recent crash

**Comment by Sgt-Imalas** [comment] 2023-03-26 00:53
so I understand that correctly, you did a game reinstall?

**Comment by rrnk235** [comment] 2023-03-26 00:53
didnt think of that for some reason lemme see

**Comment by rrnk235** [comment] 2023-03-26 01:00
reinstall didn not fix it sadly

**Comment by rrnk235** [comment] 2023-03-26 01:02
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070509/Player.log)

after reinstall just incase somthing changed

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:06
[DebugInformationLogger_dev.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070513/DebugInformationLogger_dev.zip)

I wrote a tiny logging mod that delivers some more information about the part that is crashing, can you add that mod and post me the log with it active?

**Comment by rrnk235** [comment] 2023-03-26 01:07
whats the mod?

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:08
it logs the two components that should exist, telling me which one causes the crash
[(how to install)](https://forums.kleientertainment.com/forums/topic/138444-beta-fast-track-performance-mod-for-oxygen-not-included/)

**Comment by rrnk235** [comment] 2023-03-26 01:09
the fast track mod?

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:10
no, that just has a guide on how to install local mods

**Comment by rrnk235** [comment] 2023-03-26 01:11
i do not see klei in appdata documents theres no files there

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:12
%UserProfile%, not appdata

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:13
in your case:
C:\Users\emmen\OneDrive\Documents\Klei\OxygenNotIncluded\mods\local\

**Comment by rrnk235** [comment] 2023-03-26 01:13
yea found it lol

**Comment by rrnk235** [comment] 2023-03-26 01:16
i beleive i did it right lol

**Comment by rrnk235** [comment] 2023-03-26 01:17
would it show up in the mods tab if so i did it wrong

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:19
yes it would, you need to take the folder thats inside of the zip and put it into that \local\ folder

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:20
apart from that, which button did you use to generate the custom cluster, the "normal" one or the one inside of the cluster menu?
if it was the first one, try using the "Generate Cluster" button inside of the custom cluster menu

**Comment by rrnk235** [comment] 2023-03-26 01:20
both buttons

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:21
I see.. probably doesnt make a difference to the crash

**Comment by rrnk235** [comment] 2023-03-26 01:21
in documnets in mod folder correct?\

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:21
C:\Users\emmen\OneDrive\Documents\Klei\OxygenNotIncluded\mods\local\[insert the folder here]
you may need to create the "local" folder

**Comment by rrnk235** [comment] 2023-03-26 01:22
does not exist

**Comment by rrnk235** [comment] 2023-03-26 01:22
at least the local folder doesnt

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:22
then you need to create one

**Comment by rrnk235** [comment] 2023-03-26 01:23
ok should be done corectley now

**Comment by rrnk235** [comment] 2023-03-26 01:24
ok got it now what lol just run it till it crashes?

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:24
With that mod enabled, yes

**Comment by rrnk235** [comment] 2023-03-26 01:26
ok done now what?

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:26
log please

**Comment by rrnk235** [comment] 2023-03-26 01:26
playerlog?

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:27
yes

**Comment by rrnk235** [comment] 2023-03-26 01:27
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11070545/Player.log)

**Comment by rrnk235** [comment] 2023-03-26 01:29
i wish i could understand it lol im reading it kinda seeing where the error starts but dont understand it after that lol youre a mad man XD

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:30
its even more wtf.
this is the method in question:
`public void NewSaveGamePrefab()
    {
        if (prefab_NewSaveGame != null && SaveGame.Instance == null)
        {
            Util.KInstantiate(prefab_NewSaveGame, base.gameObject);
        }
    }`
I check if either prefab_NewSaveGame or base.gameObject exist - both exist
yet the crash still says "one of them doesnt exist"
w t f

**Comment by rrnk235** [comment] 2023-03-26 01:31
wtf i kinda understood that lol

**Comment by rrnk235** [comment] 2023-03-26 01:32
i was wayoff what i thought the prob was

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:34
it also crashes after the vanilla world gen was successful (If you start it via the normal button, I dont modify the worldgen at all)
so after that has been (I might add: successfully) run, it crashes

**Comment by rrnk235** [comment] 2023-03-26 01:35
thats what i did last time and it crashed

**Comment by rrnk235** [comment] 2023-03-26 01:36
ohh somthing new

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:37
I know (I have detailed logging added to the log if the cluster is custom generated)

but _something else_ causes that crash

**Comment by rrnk235** [comment] 2023-03-26 01:38
![image](https://user-images.githubusercontent.com/128940196/227750564-e91c1394-31c9-4385-ad7b-cc3dd720b063.png)

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:39
thats just a _regular_ worldgen failure

do you have other savegames?

**Comment by rrnk235** [comment] 2023-03-26 01:39
yes i do

**Comment by rrnk235** [comment] 2023-03-26 01:39
a couple over the years lol

**Comment by rrnk235** [comment] 2023-03-26 01:40
there my well lets just say doomed colonies lol

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:40
ok

**Comment by rrnk235** [comment] 2023-03-26 01:46
seems like i can load up myold save

**Comment by rrnk235** [comment] 2023-03-26 01:47
ok so it gets weirder

**Comment by rrnk235** [comment] 2023-03-26 01:48
i load in on no sweat nd it works just fine its broken on survival

**Comment by rrnk235** [comment] 2023-03-26 01:49
yea works every time on no sweat

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:50
generating a custom cluster on no sweat works?

**Comment by rrnk235** [comment] 2023-03-26 01:50
or its just magically working

**Comment by rrnk235** [comment] 2023-03-26 01:50
somehow idk what idk why but its generating simple clusters lemme add geodes and all see if i break it

**Comment by rrnk235** [comment] 2023-03-26 01:52
sooooo it works now XD

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:52
the generation itself isn't directly related to the crash, if it works, it should work

**Comment by rrnk235** [comment] 2023-03-26 01:53
lemme enable some mods andhope

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:54
did it start working after you loaded another savegame?

**Comment by rrnk235** [comment] 2023-03-26 01:55
i beleive so

**Comment by rrnk235** [comment] 2023-03-26 01:57
yes i even enabledmods still works

**Comment by rrnk235** [comment] 2023-03-26 01:57
tysm i asppreciate youre time more than you know youre amazing

**Comment by Sgt-Imalas** [comment] 2023-03-26 01:58
great.

I strongly assume that this is some sort of base game bug that only ALMOST crashes in base game, but crashes with my mod enabled. 
If I got that correctly, loading a savegame before may eliminates it

**Comment by rrnk235** [comment] 2023-03-26 02:01
probably i havent playedit in a while to the point most of my save files are now broken so ima keep thos og save files feels like i have a relic lol

**Comment by Sgt-Imalas** [comment] 2023-03-26 02:02
but it is likely dependant on external factors like system speed, hard drive speed, etc, a "magical" bug (hence why I couldn't reproduce it)
sadly oni is littered by such issues, these are often race conditions - 2 components start up at the same time, and the game just assumes that one is ready when the other needs it - if that doesnt happens (such as here) - crash

**Comment by Sgt-Imalas** [comment] 2023-03-26 02:04
Ill close this issue, if it happens again, try redoing the things you done here (such as loading a savegame), that will likely fix it again

**Closed by Sgt-Imalas** 2023-03-26 02:04 UTC
Labels: bug

**Comment by Sgt-Imalas** [comment] 2023-03-26 02:06
(you could leave a comment on steam, indicating that the crash was fixed)

**Comment by rrnk235** [comment] 2023-03-26 02:13
i will deff do that and the solution if somone comes across it

**Comment by Sgt-Imalas** [comment] 2023-03-26 02:17
just the fixed part is enough, I'll update the description tomorrow, explaining the bug and how to circumvent it (Ill be also looking into options to initialize that mysterious missing component earlier to circumvent the issue)

**Comment by rrnk235** [comment] 2023-03-26 02:19
well i really hope the info helps if you need anything else contact me on steam its the same name as on here i dont use github much so its unlikley ill check it

**Comment by rrnk235** [comment] 2023-03-26 02:22
also mod sugesstion in the mod that changes dupes stats at start would it be viable to be able to remove negatives entirly just food for thought
