### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by faltonico** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#81] opened 2023-10-09 03:35 UTC
### Which Mod?

Scan & Relay Satellites (DLC)

### Description of the bug/crash

Sometimes, after a long session, the automation receivers get "out of range" on their own, even though they were working before.
![Oxygen Not Included 09-10-2023 0_22_08](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/23186360/def964e8-dea0-43d0-8814-c6428d4ca388)

![Oxygen Not Included 09-10-2023 0_28_16](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/23186360/cb42bae5-5051-48be-9896-5b089669f8cd)

On this particular example (it has happened to me a couple times now), the receiver got stuck at the green position, even though the transmitter is currently red.

![Oxygen Not Included 09-10-2023 0_34_28](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/23186360/d9d8f90c-34e2-4f94-9a08-cced10f3896c)

### Steps To Reproduce

Play for a while, a long while, and the receiver will lose contact on its own.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12842495/Player.log)

**Comment by faltonico** [comment] 2023-10-09 06:53
Here is a video:
https://gemoo.com/tools/upload-video/share/569898384385413120?codeId=v69qrL88R7Qwz&card=569898380476321792

**Comment by Sgt-Imalas** [comment] 2023-10-11 19:53
Were you adding/removing satellites in the connection between them?
I just found a bug that having multiple satellites in one hex; then removing one would accidentally delete the connections to that hex, even tho there was still a satellite in there

**Comment by faltonico** [comment] 2023-10-12 22:57
Short answer: No.
Convoluted answer: After placing them, like 200 cycles or so, i haven't moved them, but here is the thing, i did move them around when setting them up, because with only the 2 upper ones, i couldn't connect the receivers. And i think they should had worked with just 2, cause they are not over 5 tiles away.

**Comment by Sgt-Imalas** [comment] 2023-10-13 14:23
Im currently doing a bit of a rewrite of that logic, and that was one of the bugs I found.
another was that it would also remove a satellite, if you would try to connect to something (a rocket f.e.) on the tile the satellite sat on. I assume its might be caused by that

**Comment by faltonico** [comment] 2023-10-14 00:24
Glad to hear that! And thank you for making this mods, they make the game absolutely amazing to play.

**Comment by Sgt-Imalas** [comment] 2023-10-18 12:09
this bug should now be fixed in 1.2.2

**Closed by Sgt-Imalas** 2023-10-18 12:09 UTC
Labels: bug
